import{useEffect,useMemo,useState}from"react";import{ArrowRight,ChevronRight,LayoutGrid,LogOut,Menu,Plus,ReceiptText,TrendingUp,Users,X}from"lucide-react";
const API=import.meta.env.VITE_API_URL||"https://splitmate.hrms.ssym.co.in";
type Group={id:string;name:string;emoji:string;member_count:number;total_spent:number};type Expense={id:string;title:string;category:string;amount:number;expense_date:string;paid_by_name:string};type Member={id:string;name:string;email:string};type Detail={id:string;name:string;emoji:string;members:Member[];expenses:Expense[]};type Balance={id:string;name:string;balance:number};
async function request(path:string,token?:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});const d=await r.json();if(!r.ok)throw new Error(d.message||"Request failed");return d}
export default function App(){
 const[token,setToken]=useState(()=>localStorage.getItem("splitmate-token")||"");const[user,setUser]=useState(()=>JSON.parse(localStorage.getItem("splitmate-user")||"null"));const[email,setEmail]=useState("demo@splitmate.app");const[password,setPassword]=useState("Demo@123");const[groups,setGroups]=useState<Group[]>([]);const[detail,setDetail]=useState<Detail|null>(null);const[balances,setBalances]=useState<Balance[]>([]);const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[menu,setMenu]=useState(false);
 useEffect(()=>{if(!token)return;request("/api/groups",token).then(async(g)=>{setGroups(g);if(g[0]){setDetail(await request(`/api/groups/${g[0].id}`,token));setBalances(await request(`/api/groups/${g[0].id}/balances`,token))}}).catch(e=>setError(e.message))},[token]);
 async function login(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");try{const d=await request("/api/auth/login",undefined,{method:"POST",body:JSON.stringify({email,password})});localStorage.setItem("splitmate-token",d.token);localStorage.setItem("splitmate-user",JSON.stringify(d.user));setToken(d.token);setUser(d.user)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 function logout(){localStorage.clear();setToken("");setUser(null)}
 const total=useMemo(()=>detail?.expenses.reduce((s,e)=>s+e.amount,0)||0,[detail]);
 if(!token||!user)return <Login email={email}password={password}setEmail={setEmail}setPassword={setPassword}submit={login}error={error}loading={loading}/>;
 return <div className="app"><aside className={menu?"side open":"side"}><div className="brand"><b>S</b>splitmate.</div><button className="close" onClick={()=>setMenu(false)}><X/></button><nav><a className="active"><LayoutGrid/>Overview</a><a><Users/>Groups</a><a><ReceiptText/>Expenses</a><a><TrendingUp/>Insights</a></nav><div className="profile"><span>{user.name[0]}</span><div><strong>{user.name}</strong><small>{user.email}</small></div></div><button className="logout" onClick={logout}><LogOut/>Sign out</button></aside>
 <main className="main"><header><button className="menu" onClick={()=>setMenu(true)}><Menu/></button><div><small>YOUR SHARED SPACE</small><h1>Money is easier together.</h1></div><button className="new"><Plus/>Add expense</button></header>{error&&<div className="error">{error}</div>}
 <section className="balance-hero"><div><small>TOTAL GROUP SPEND</small><h2>₹{total.toLocaleString("en-IN")}</h2><p>{detail?.name} · {detail?.members.length||0} people</p></div><div className="avatars">{detail?.members.map((m,i)=><span style={{zIndex:9-i}} key={m.id}>{m.name[0]}</span>)}</div><div className="shape"/></section>
 <section className="quick-grid"><article><span>You are owed</span><strong>₹{Math.max(0,balances.find(b=>b.id===user.id)?.balance||0).toLocaleString("en-IN")}</strong><i>Across this group</i></article><article><span>Your share</span><strong>₹{Math.round(total/(detail?.members.length||1)).toLocaleString("en-IN")}</strong><i>Equal split</i></article><article className="settle"><div><span>All caught up?</span><strong>Record a payment</strong></div><button><ArrowRight/></button></article></section>
 <div className="dashboard-grid"><section className="panel"><div className="head"><div><small>RECENT ACTIVITY</small><h3>Group expenses</h3></div><button>View all</button></div><div className="expenses">{detail?.expenses.map((e)=><div className="expense"key={e.id}><i>{iconFor(e.category)}</i><div><strong>{e.title}</strong><span>{e.paid_by_name} paid · {new Date(e.expense_date).toLocaleDateString("en-IN",{day:"numeric",month:"short"})}</span></div><b>₹{e.amount.toLocaleString("en-IN")}</b><ChevronRight/></div>)}</div></section>
 <section className="panel"><div className="head"><div><small>BALANCES</small><h3>Who owes what</h3></div></div><div className="balances">{balances.map((b)=><div key={b.id}><span>{b.name[0]}</span><div><strong>{b.name}</strong><small>{b.balance>=0?"gets back":"owes"}</small></div><b className={b.balance>=0?"positive":"negative"}>{b.balance>=0?"+":"−"}₹{Math.abs(b.balance).toLocaleString("en-IN")}</b></div>)}</div></section></div>
 <section className="groups"><div className="head"><div><small>YOUR GROUPS</small><h3>Keep every plan organised</h3></div></div><div className="group-list">{groups.map(g=><article key={g.id}><span>{g.emoji}</span><div><strong>{g.name}</strong><small>{g.member_count} members</small></div><b>₹{g.total_spent.toLocaleString("en-IN")}</b></article>)}<button><Plus/>New group</button></div></section>
 </main></div>
}
function iconFor(category:string){return({Stay:"⌂",Food:"◉",Travel:"↗"}as Record<string,string>)[category]||"₹"}
function Login({email,password,setEmail,setPassword,submit,error,loading}:{email:string;password:string;setEmail:(v:string)=>void;setPassword:(v:string)=>void;submit:(e:React.FormEvent)=>void;error:string;loading:boolean}){return <main className="login"><section><div className="brand light"><b>S</b>splitmate.</div><div className="login-copy"><p>SHARED EXPENSES, ZERO AWKWARDNESS</p><h1>Trips are memorable.<br/><em>Splitting bills should not be.</em></h1><span>Track shared spending, understand balances, and settle up without spreadsheets.</span></div><div className="mini-card"><span>🌴</span><div><small>GOA WEEKEND</small><strong>₹11,850 shared fairly</strong></div><b>3 friends</b></div></section><form onSubmit={submit}><p>WELCOME BACK</p><h2>Sign in to SplitMate</h2><label>Email<input type="email"value={email}onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password"value={password}onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button disabled={loading}>{loading?"Opening your groups…":"Continue"}<ArrowRight/></button><div className="demo"><strong>Demo login</strong><span>demo@splitmate.app · Demo@123</span></div></form></main>}
